require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ContentTemplatesController do

  def mock_content_template(stubs={})
    @mock_content_template ||= mock_model(ContentTemplate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all content_templates as @content_templates" do
      ContentTemplate.stub(:all) { [mock_content_template] }
      get :index
      assigns(:content_templates).should eq([mock_content_template])
    end
  end

  describe "GET show" do
    it "assigns the requested content_template as @content_template" do
      ContentTemplate.stub(:find).with("37") { mock_content_template }
      get :show, :id => "37"
      assigns(:content_template).should be(mock_content_template)
    end
  end

  describe "GET new" do
    it "assigns a new content_template as @content_template" do
      ContentTemplate.stub(:new) { mock_content_template }
      get :new
      assigns(:content_template).should be(mock_content_template)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_template as @content_template" do
      ContentTemplate.stub(:find).with("37") { mock_content_template }
      get :edit, :id => "37"
      assigns(:content_template).should be(mock_content_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created content_template as @content_template" do
        ContentTemplate.stub(:new).with({'these' => 'params'}) { mock_content_template(:save => true) }
        post :create, :content_template => {'these' => 'params'}
        assigns(:content_template).should be(mock_content_template)
      end

      it "redirects to the created content_template" do
        ContentTemplate.stub(:new) { mock_content_template(:save => true) }
        post :create, :content_template => {}
        response.should redirect_to(content_template_url(mock_content_template))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_template as @content_template" do
        ContentTemplate.stub(:new).with({'these' => 'params'}) { mock_content_template(:save => false) }
        post :create, :content_template => {'these' => 'params'}
        assigns(:content_template).should be(mock_content_template)
      end

      it "re-renders the 'new' template" do
        ContentTemplate.stub(:new) { mock_content_template(:save => false) }
        post :create, :content_template => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_template" do
        ContentTemplate.stub(:find).with("37") { mock_content_template }
        mock_content_template.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :content_template => {'these' => 'params'}
      end

      it "assigns the requested content_template as @content_template" do
        ContentTemplate.stub(:find) { mock_content_template(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:content_template).should be(mock_content_template)
      end

      it "redirects to the content_template" do
        ContentTemplate.stub(:find) { mock_content_template(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(content_template_url(mock_content_template))
      end
    end

    describe "with invalid params" do
      it "assigns the content_template as @content_template" do
        ContentTemplate.stub(:find) { mock_content_template(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:content_template).should be(mock_content_template)
      end

      it "re-renders the 'edit' template" do
        ContentTemplate.stub(:find) { mock_content_template(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_template" do
      ContentTemplate.stub(:find).with("37") { mock_content_template }
      mock_content_template.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the content_templates list" do
      ContentTemplate.stub(:find) { mock_content_template }
      delete :destroy, :id => "1"
      response.should redirect_to(content_templates_url)
    end
  end

end
