require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::CuratedFeedsController do

  def mock_curated_feed(stubs={})
    @mock_curated_feed ||= mock_model(Admin::CuratedFeed, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all admin_curated_feeds as @admin_curated_feeds" do
      Admin::CuratedFeed.stub(:all) { [mock_curated_feed] }
      get :index
      assigns(:admin_curated_feeds).should eq([mock_curated_feed])
    end
  end

  describe "GET show" do
    it "assigns the requested curated_feed as @curated_feed" do
      Admin::CuratedFeed.stub(:find).with("37") { mock_curated_feed }
      get :show, :id => "37"
      assigns(:curated_feed).should be(mock_curated_feed)
    end
  end

  describe "GET new" do
    it "assigns a new curated_feed as @curated_feed" do
      Admin::CuratedFeed.stub(:new) { mock_curated_feed }
      get :new
      assigns(:curated_feed).should be(mock_curated_feed)
    end
  end

  describe "GET edit" do
    it "assigns the requested curated_feed as @curated_feed" do
      Admin::CuratedFeed.stub(:find).with("37") { mock_curated_feed }
      get :edit, :id => "37"
      assigns(:curated_feed).should be(mock_curated_feed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created curated_feed as @curated_feed" do
        Admin::CuratedFeed.stub(:new).with({'these' => 'params'}) { mock_curated_feed(:save => true) }
        post :create, :curated_feed => {'these' => 'params'}
        assigns(:curated_feed).should be(mock_curated_feed)
      end

      it "redirects to the created curated_feed" do
        Admin::CuratedFeed.stub(:new) { mock_curated_feed(:save => true) }
        post :create, :curated_feed => {}
        response.should redirect_to(admin_curated_feed_url(mock_curated_feed))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curated_feed as @curated_feed" do
        Admin::CuratedFeed.stub(:new).with({'these' => 'params'}) { mock_curated_feed(:save => false) }
        post :create, :curated_feed => {'these' => 'params'}
        assigns(:curated_feed).should be(mock_curated_feed)
      end

      it "re-renders the 'new' template" do
        Admin::CuratedFeed.stub(:new) { mock_curated_feed(:save => false) }
        post :create, :curated_feed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curated_feed" do
        Admin::CuratedFeed.stub(:find).with("37") { mock_curated_feed }
        mock_admin_curated_feed.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :curated_feed => {'these' => 'params'}
      end

      it "assigns the requested curated_feed as @curated_feed" do
        Admin::CuratedFeed.stub(:find) { mock_curated_feed(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:curated_feed).should be(mock_curated_feed)
      end

      it "redirects to the curated_feed" do
        Admin::CuratedFeed.stub(:find) { mock_curated_feed(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(admin_curated_feed_url(mock_curated_feed))
      end
    end

    describe "with invalid params" do
      it "assigns the curated_feed as @curated_feed" do
        Admin::CuratedFeed.stub(:find) { mock_curated_feed(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:curated_feed).should be(mock_curated_feed)
      end

      it "re-renders the 'edit' template" do
        Admin::CuratedFeed.stub(:find) { mock_curated_feed(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curated_feed" do
      Admin::CuratedFeed.stub(:find).with("37") { mock_curated_feed }
      mock_admin_curated_feed.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the admin_curated_feeds list" do
      Admin::CuratedFeed.stub(:find) { mock_curated_feed }
      delete :destroy, :id => "1"
      response.should redirect_to(admin_curated_feeds_url)
    end
  end

end
